import '../metrics/mark.dart';

// ---------------------------------------------------------------------------
// Decree — Performance Report
// ---------------------------------------------------------------------------

/// A comprehensive performance report generated by [Colossus].
///
/// Aggregates all collected metrics into a single summary that can be
/// logged, exported, or displayed.
///
/// ## Why "Decree"?
///
/// A decree is an official pronouncement. The Decree is the Colossus's
/// official verdict on your app's performance health.
///
/// ```dart
/// final decree = Colossus.instance.decree();
/// print(decree.summary);
/// print('FPS: ${decree.avgFps}');
/// print('Jank rate: ${decree.jankRate}%');
/// print('Avg page load: ${decree.avgPageLoad.inMilliseconds}ms');
/// ```
class Decree {
  /// Session start time.
  final DateTime sessionStart;

  /// Session end time (when the decree was generated).
  final DateTime generatedAt;

  /// Total number of frames measured.
  final int totalFrames;

  /// Number of janky frames (> 16ms).
  final int jankFrames;

  /// Average frames per second.
  final double avgFps;

  /// Average frame build duration.
  final Duration avgBuildTime;

  /// Average frame raster duration.
  final Duration avgRasterTime;

  /// Jank rate as a percentage (0.0–100.0).
  double get jankRate => totalFrames > 0 ? (jankFrames / totalFrames) * 100 : 0;

  /// All page load measurements.
  final List<PageLoadMark> pageLoads;

  /// Average page load duration.
  Duration get avgPageLoad {
    if (pageLoads.isEmpty) return Duration.zero;
    final totalUs = pageLoads.fold<int>(
      0,
      (sum, m) => sum + m.duration.inMicroseconds,
    );
    return Duration(microseconds: totalUs ~/ pageLoads.length);
  }

  /// Slowest page load.
  PageLoadMark? get slowestPageLoad {
    if (pageLoads.isEmpty) return null;
    return pageLoads.reduce((a, b) => a.duration > b.duration ? a : b);
  }

  /// Number of live Pillar instances.
  final int pillarCount;

  /// Number of total DI instances.
  final int totalInstances;

  /// Current leak suspects.
  final List<LeakSuspect> leakSuspects;

  /// Widget rebuild counts by label.
  final Map<String, int> rebuildsPerWidget;

  /// Total widget rebuilds tracked.
  int get totalRebuilds =>
      rebuildsPerWidget.values.fold<int>(0, (sum, c) => sum + c);

  /// Top N widgets by rebuild count.
  List<MapEntry<String, int>> topRebuilders([int n = 5]) {
    final sorted = rebuildsPerWidget.entries.toList()
      ..sort((a, b) => b.value.compareTo(a.value));
    return sorted.take(n).toList();
  }

  /// Overall health verdict.
  PerformanceHealth get health {
    if (jankRate > 10 || leakSuspects.isNotEmpty) {
      return PerformanceHealth.poor;
    }
    if (jankRate > 5 || avgPageLoad.inMilliseconds > 500) {
      return PerformanceHealth.fair;
    }
    return PerformanceHealth.good;
  }

  /// Creates a [Decree].
  Decree({
    required this.sessionStart,
    required this.totalFrames,
    required this.jankFrames,
    required this.avgFps,
    required this.avgBuildTime,
    required this.avgRasterTime,
    required this.pageLoads,
    required this.pillarCount,
    required this.totalInstances,
    required this.leakSuspects,
    required this.rebuildsPerWidget,
    DateTime? generatedAt,
  }) : generatedAt = generatedAt ?? DateTime.now();

  /// Converts this decree to a JSON-serializable map.
  Map<String, dynamic> toMap() => {
    'sessionStart': sessionStart.toIso8601String(),
    'generatedAt': generatedAt.toIso8601String(),
    'durationSeconds': generatedAt.difference(sessionStart).inSeconds,
    'health': health.name,
    'pulse': {
      'totalFrames': totalFrames,
      'jankFrames': jankFrames,
      'jankRate': (jankRate * 100).roundToDouble() / 100,
      'avgFps': (avgFps * 10).roundToDouble() / 10,
      'avgBuildTimeUs': avgBuildTime.inMicroseconds,
      'avgRasterTimeUs': avgRasterTime.inMicroseconds,
    },
    'stride': {
      'totalPageLoads': pageLoads.length,
      'avgPageLoadMs': avgPageLoad.inMilliseconds,
      'pageLoads': pageLoads.map((p) => p.toMap()).toList(),
      if (slowestPageLoad case final slowest?)
        'slowestPageLoad': slowest.toMap(),
    },
    'vessel': {
      'pillarCount': pillarCount,
      'totalInstances': totalInstances,
      'leakSuspects': leakSuspects.map((s) => s.toMap()).toList(),
    },
    'echo': {
      'totalRebuilds': totalRebuilds,
      'rebuildsPerWidget': rebuildsPerWidget,
      'topRebuilders': Map.fromEntries(topRebuilders()),
    },
  };

  /// Human-readable summary.
  String get summary {
    final buf = StringBuffer()
      ..writeln('═══ Colossus Performance Decree ═══')
      ..writeln('Session: ${_fmt(sessionStart)} → ${_fmt(generatedAt)}')
      ..writeln('Duration: ${generatedAt.difference(sessionStart).inSeconds}s')
      ..writeln()
      ..writeln('─── Pulse (Frames) ───')
      ..writeln('  FPS: ${avgFps.toStringAsFixed(1)}')
      ..writeln('  Frames: $totalFrames ($jankFrames jank)')
      ..writeln('  Jank rate: ${jankRate.toStringAsFixed(1)}%')
      ..writeln('  Avg build: ${avgBuildTime.inMicroseconds}µs')
      ..writeln('  Avg raster: ${avgRasterTime.inMicroseconds}µs')
      ..writeln()
      ..writeln('─── Stride (Page Loads) ───')
      ..writeln('  Total: ${pageLoads.length}')
      ..writeln('  Avg: ${avgPageLoad.inMilliseconds}ms');
    final slowest = slowestPageLoad;
    if (slowest != null) {
      buf.writeln(
        '  Slowest: ${slowest.path} (${slowest.duration.inMilliseconds}ms)',
      );
    }
    buf
      ..writeln()
      ..writeln('─── Vessel (Memory) ───')
      ..writeln('  Pillars: $pillarCount')
      ..writeln('  Total instances: $totalInstances')
      ..writeln('  Leak suspects: ${leakSuspects.length}');
    for (final suspect in leakSuspects) {
      buf.writeln('    ⚠ ${suspect.typeName} (${suspect.age.inSeconds}s)');
    }
    buf
      ..writeln()
      ..writeln('─── Echo (Rebuilds) ───')
      ..writeln('  Total: $totalRebuilds');
    for (final entry in topRebuilders()) {
      buf.writeln('    ${entry.key}: ${entry.value}');
    }
    buf
      ..writeln()
      ..writeln('─── Verdict: ${health.name.toUpperCase()} ───')
      ..writeln('═══════════════════════════════════');
    return buf.toString();
  }

  static String _fmt(DateTime dt) =>
      '${dt.hour.toString().padLeft(2, '0')}:'
      '${dt.minute.toString().padLeft(2, '0')}:'
      '${dt.second.toString().padLeft(2, '0')}';

  @override
  String toString() =>
      'Decree(health=${health.name}, fps=$avgFps, '
      'jank=${jankRate.toStringAsFixed(1)}%, '
      'pageLoads=${pageLoads.length}, '
      'leaks=${leakSuspects.length})';
}

/// Overall performance health rating.
enum PerformanceHealth {
  /// Excellent performance — low jank, no leaks.
  good,

  /// Acceptable performance — some jank or slow page loads.
  fair,

  /// Poor performance — high jank rate or memory leaks detected.
  poor,
}
