name: titan_workspace
publish_to: none

environment:
  sdk: ">=3.10.3 <4.0.0"

dev_dependencies:
  melos: ^7.4.0

workspace:
  - packages/titan
  - packages/titan_bastion
  - packages/titan_atlas
  - packages/titan_argus
  - packages/titan_colossus
  - packages/titan_example
