import 'dart:convert';

// ---------------------------------------------------------------------------
// Imprint — Recorded interaction event
// ---------------------------------------------------------------------------

/// **Imprint** — a single recorded user interaction event.
///
/// Every tap, scroll, drag, and swipe leaves an [Imprint] in the
/// session recording. An ordered list of Imprints forms a complete
/// interaction session that can be replayed by [Phantom].
///
/// ## Why "Imprint"?
///
/// Like a fossil imprint preserving the shape of ancient life, an
/// Imprint preserves the exact gesture a user performed — position,
/// timing, pressure — ready to be replayed as a faithful echo of
/// the original interaction.
///
/// ## Structure
///
/// ```dart
/// final imprint = Imprint(
///   type: ImprintType.pointerDown,
///   position: Offset(100, 200),
///   timestamp: Duration(milliseconds: 1200),
///   pointer: 1,
///   buttons: 1,
/// );
/// ```
class Imprint {
  /// The type of pointer event this imprint represents.
  final ImprintType type;

  /// The position in logical pixels where the event occurred.
  ///
  /// Stored as [dx, dy] for serialization. Use [positionX] and
  /// [positionY] for direct access.
  final double positionX;

  /// The Y position in logical pixels.
  final double positionY;

  /// Time elapsed since the recording session started.
  ///
  /// Used by [Phantom] to schedule replay timing.
  final Duration timestamp;

  /// The pointer identifier (finger/stylus/mouse button).
  final int pointer;

  /// The device kind (touch = 0, mouse = 1, stylus = 2, etc.).
  final int deviceKind;

  /// Bitfield of pressed buttons (1 = primary, 2 = secondary, etc.).
  final int buttons;

  /// The movement delta since the last event, X component.
  final double deltaX;

  /// The movement delta since the last event, Y component.
  final double deltaY;

  /// Scroll delta X (for mouse scroll events).
  final double scrollDeltaX;

  /// Scroll delta Y (for mouse scroll events).
  final double scrollDeltaY;

  /// Pressure applied (0.0–1.0, where supported).
  final double pressure;

  // -----------------------------------------------------------------------
  // Key event fields (for keyDown, keyUp, keyRepeat)
  // -----------------------------------------------------------------------

  /// The logical keyboard key identifier.
  ///
  /// Maps to [LogicalKeyboardKey.keyId]. Only set for key events.
  final int? keyId;

  /// The physical keyboard key identifier.
  ///
  /// Maps to [PhysicalKeyboardKey.usbHidUsage]. Only set for key events.
  final int? physicalKey;

  /// The character generated by this key event (if any).
  ///
  /// For example, pressing 'A' produces `'a'` (or `'A'` with shift).
  final String? character;

  // -----------------------------------------------------------------------
  // Text input fields (for textInput, textAction)
  // -----------------------------------------------------------------------

  /// The text content at the time of this imprint.
  ///
  /// Only set for [ImprintType.textInput] events.
  final String? text;

  /// The selection base offset (cursor start).
  final int? selectionBase;

  /// The selection extent offset (cursor end).
  final int? selectionExtent;

  /// The composing region start.
  final int? composingBase;

  /// The composing region end.
  final int? composingExtent;

  /// The text input action identifier.
  ///
  /// Only set for [ImprintType.textAction] events.
  /// Maps to [TextInputAction.index].
  final int? textInputAction;

  /// Optional field identifier for text tracking.
  ///
  /// Associates text input events with a specific text field.
  final String? fieldId;

  /// Creates an [Imprint] from a recorded event.
  const Imprint({
    required this.type,
    required this.positionX,
    required this.positionY,
    required this.timestamp,
    this.pointer = 0,
    this.deviceKind = 0,
    this.buttons = 0,
    this.deltaX = 0,
    this.deltaY = 0,
    this.scrollDeltaX = 0,
    this.scrollDeltaY = 0,
    this.pressure = 1.0,
    this.keyId,
    this.physicalKey,
    this.character,
    this.text,
    this.selectionBase,
    this.selectionExtent,
    this.composingBase,
    this.composingExtent,
    this.textInputAction,
    this.fieldId,
  });

  /// Converts this imprint to a JSON-serializable map.
  Map<String, dynamic> toMap() => {
    'type': type.name,
    'x': positionX,
    'y': positionY,
    'ts': timestamp.inMicroseconds,
    'pointer': pointer,
    'deviceKind': deviceKind,
    'buttons': buttons,
    if (deltaX != 0) 'dx': deltaX,
    if (deltaY != 0) 'dy': deltaY,
    if (scrollDeltaX != 0) 'sdx': scrollDeltaX,
    if (scrollDeltaY != 0) 'sdy': scrollDeltaY,
    if (pressure != 1.0) 'pressure': pressure,
    if (keyId != null) 'keyId': keyId,
    if (physicalKey != null) 'physicalKey': physicalKey,
    if (character != null) 'char': character,
    if (text != null) 'text': text,
    if (selectionBase != null) 'selBase': selectionBase,
    if (selectionExtent != null) 'selExtent': selectionExtent,
    if (composingBase != null) 'compBase': composingBase,
    if (composingExtent != null) 'compExtent': composingExtent,
    if (textInputAction != null) 'action': textInputAction,
    if (fieldId != null) 'fieldId': fieldId,
  };

  /// Creates an [Imprint] from a deserialized map.
  factory Imprint.fromMap(Map<String, dynamic> map) {
    return Imprint(
      type: ImprintType.values.byName(map['type'] as String),
      positionX: (map['x'] as num).toDouble(),
      positionY: (map['y'] as num).toDouble(),
      timestamp: Duration(microseconds: map['ts'] as int),
      pointer: map['pointer'] as int? ?? 0,
      deviceKind: map['deviceKind'] as int? ?? 0,
      buttons: map['buttons'] as int? ?? 0,
      deltaX: (map['dx'] as num?)?.toDouble() ?? 0,
      deltaY: (map['dy'] as num?)?.toDouble() ?? 0,
      scrollDeltaX: (map['sdx'] as num?)?.toDouble() ?? 0,
      scrollDeltaY: (map['sdy'] as num?)?.toDouble() ?? 0,
      pressure: (map['pressure'] as num?)?.toDouble() ?? 1.0,
      keyId: map['keyId'] as int?,
      physicalKey: map['physicalKey'] as int?,
      character: map['char'] as String?,
      text: map['text'] as String?,
      selectionBase: map['selBase'] as int?,
      selectionExtent: map['selExtent'] as int?,
      composingBase: map['compBase'] as int?,
      composingExtent: map['compExtent'] as int?,
      textInputAction: map['action'] as int?,
      fieldId: map['fieldId'] as String?,
    );
  }

  @override
  String toString() =>
      'Imprint(${type.name}, ($positionX, $positionY), '
      '${timestamp.inMilliseconds}ms)';
}

// ---------------------------------------------------------------------------
// ImprintType — pointer event types
// ---------------------------------------------------------------------------

/// The type of interaction captured in an [Imprint].
enum ImprintType {
  // --- Pointer events ---

  /// A pointer (finger/mouse) pressed down.
  pointerDown,

  /// A pointer moved while pressed.
  pointerMove,

  /// A pointer was released.
  pointerUp,

  /// A pointer was cancelled (e.g. system gesture).
  pointerCancel,

  /// The mouse pointer hovered (no buttons pressed).
  pointerHover,

  /// Mouse wheel scroll event.
  pointerScroll,

  /// Mouse wheel scroll with inertia.
  pointerScrollInertiaCancel,

  /// Touch/stylus added to the system.
  pointerAdded,

  /// Touch/stylus removed from the system.
  pointerRemoved,

  /// Trackpad pan/zoom started.
  pointerPanZoomStart,

  /// Trackpad pan/zoom update.
  pointerPanZoomUpdate,

  /// Trackpad pan/zoom ended.
  pointerPanZoomEnd,

  // --- Key events ---

  /// A physical key was pressed down.
  keyDown,

  /// A physical key was released.
  keyUp,

  /// A held key generated a repeat event.
  keyRepeat,

  // --- Text input events ---

  /// A text editing state change (text content + cursor position).
  ///
  /// Captured from [ShadeTextController] or soft keyboard input.
  textInput,

  /// A text input action (done, next, newline, etc.).
  textAction,
}

// ---------------------------------------------------------------------------
// ShadeSession — Complete recorded session
// ---------------------------------------------------------------------------

/// **ShadeSession** — a complete recorded interaction session.
///
/// Contains metadata about the recording and an ordered list of
/// [Imprint]s that can be replayed by [Phantom].
///
/// ## Serialization
///
/// Sessions can be serialized to JSON for storage and later replay:
///
/// ```dart
/// final json = session.toJson();
/// final restored = ShadeSession.fromJson(json);
/// ```
class ShadeSession {
  /// A unique identifier for this session.
  final String id;

  /// Human-readable name for this session.
  final String name;

  /// When the session was recorded.
  final DateTime recordedAt;

  /// Total duration of the recording.
  final Duration duration;

  /// The screen width in logical pixels at recording time.
  final double screenWidth;

  /// The screen height in logical pixels at recording time.
  final double screenHeight;

  /// The device pixel ratio at recording time.
  final double devicePixelRatio;

  /// Ordered list of recorded events.
  final List<Imprint> imprints;

  /// Optional description or notes for this session.
  final String? description;

  /// The route path at the time recording started.
  ///
  /// Used by [Phantom] to verify the app is on the correct page
  /// before replaying. Prevents replaying events on the wrong
  /// screen, which would produce invalid results.
  final String? startRoute;

  /// Creates a [ShadeSession] with metadata and recorded events.
  const ShadeSession({
    required this.id,
    required this.name,
    required this.recordedAt,
    required this.duration,
    required this.screenWidth,
    required this.screenHeight,
    required this.devicePixelRatio,
    required this.imprints,
    this.description,
    this.startRoute,
  });

  /// The total number of recorded events.
  int get eventCount => imprints.length;

  /// Converts this session to a JSON-serializable map.
  Map<String, dynamic> toMap() => {
    'id': id,
    'name': name,
    'recordedAt': recordedAt.toIso8601String(),
    'durationUs': duration.inMicroseconds,
    'screenWidth': screenWidth,
    'screenHeight': screenHeight,
    'devicePixelRatio': devicePixelRatio,
    'eventCount': eventCount,
    if (description != null) 'description': description,
    if (startRoute != null) 'startRoute': startRoute,
    'imprints': imprints.map((i) => i.toMap()).toList(),
  };

  /// Serializes this session to a JSON string.
  ///
  /// Uses compact encoding for minimal size. For pretty-printed output,
  /// use `const JsonEncoder.withIndent('  ').convert(toMap())`.
  String toJson() => jsonEncode(toMap());

  /// Creates a [ShadeSession] from a deserialized map.
  factory ShadeSession.fromMap(Map<String, dynamic> map) {
    return ShadeSession(
      id: map['id'] as String,
      name: map['name'] as String,
      recordedAt: DateTime.parse(map['recordedAt'] as String),
      duration: Duration(microseconds: map['durationUs'] as int),
      screenWidth: (map['screenWidth'] as num).toDouble(),
      screenHeight: (map['screenHeight'] as num).toDouble(),
      devicePixelRatio: (map['devicePixelRatio'] as num).toDouble(),
      description: map['description'] as String?,
      startRoute: map['startRoute'] as String?,
      imprints: (map['imprints'] as List)
          .map((e) => Imprint.fromMap(e as Map<String, dynamic>))
          .toList(),
    );
  }

  /// Creates a [ShadeSession] from a JSON string.
  factory ShadeSession.fromJson(String json) {
    return ShadeSession.fromMap(jsonDecode(json) as Map<String, dynamic>);
  }

  @override
  String toString() =>
      'ShadeSession($name, $eventCount events, '
      '${duration.inMilliseconds}ms)';
}
